# Generated by Django 5.2.4 on 2025-07-23 14:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
