# Generated by Django 5.2.4 on 2025-07-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Itenary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('trek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itenary', to='trek.trek')),
            ],
        ),
    ]
