# Generated by Django 5.2.4 on 2025-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenary',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itenary',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='trek',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
